# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd4fb03b36410282e535f8c1ae44ae6d033563596784327a17351387440471c62f4a5ea4a2595255bf97297b6f86f3d8de5ac050ab8a5382367087b102a9a04b

test:
  secret_key_base: 343f7d5ccf03aa5d57cce3af2c0de2631e67fa39d16da21be1c46e58d24cacd9520a8dfa57dda034d36c134005f8447c5d78a45517b197d6a3872e0a7d5fc3f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
